playtron-os/playtron-os-files

- README.md
- etc/sysctl.d/50-swappiness.conf
- lib/systemd/system/create-swap.service
- sbin/create-swap.sh
along with a systemd service file to run it once during the first boot and a sysctl configuration file to lower swappiness to 1.
> Add create-swap script

- CONTRIBUTING.md
This contributor's guide is based on the same one used by Playtron OS. Links have been updated to point to this new repository.
https://github.com/playtron-os/playtron-os/pull/48
> [contributing] Add a contributor-s guide

- README.md
- sbin/create-swap.sh
Creating swap can accidentally fill up a storage device. We now check to see how much storage is available first.
> Resize fixes

- README.md
- etc/sudoers.d/playtron
- usr/bin/playtron-factory-reset
- usr/lib/systemd/system-preset/50-playtron.preset
- usr/share/polkit-1/rules.d/50-one.playtron.factory-reset.rules
- added `playtron-factory-reset` script
- added permissions to execute `playtron-factory-reset` without a sudo password
- disabled firewalld service in preset file to avoid factory reset re-enabling it
Testing:
- tested full reset on a PlaytronOS installation with `playtron-factory-reset`, worked as expected
- tested partial reset on a PlaytronOS installation with `playtron-factory-reset --preserve-user-files`, worked as expected
Sibling PR: https://github.com/playtron-os/playtron-os/pull/76
> OST-227 add factory reset script

- usr/bin/playtron-factory-reset
Change factory reset `--preserve-user-files` option to also preserve network settings. This change was made due to feedback from design.
Testing:
- ran `playtron-factory-reset --preserve-user-files`
- was not prompted for wifi settings
- did not have to login to playtron i.e. FTUE was not triggered
- wifi worked (could ssh into device)
- ran `playtron-factory-reset`
- was prompted for wifi settings
- had to login to playtron i.e. FTUE was triggered
> factory reset `--preserve-user-files` should preserve network settings

- usr/lib/systemd/system-preset/50-playtron.preset
This change adds the InputPlumber service to start on system boot. This change is also required to include the InputPlumber package: https://github.com/playtron-os/playtron-os/pull/81
> Add InputPlumber service on startup

- usr/bin/hwctl
Battery reporting should now work on more devices.
Included a default case for devices with no detected battery.
Tested on:
- Aya Neo 2
- Desktop system with no battery
> battery reporting for more than just steam deck

- usr/bin/hwctl
- usr/lib/os-release-playtron
Overriding the Fedora `os-release` file is rather involved due to all the package dependencies and so was set aside.
But having version info will be very useful, so instead, source version info from a playtron specific location for now.
Will need to update the `playtron-os-files` package with every build. Perhaps we should also align the package version with the OS version.
> add and source playtron specific versioning info

- usr/bin/hwctl
Only part of PTCORE-222.
This allows playserve to obtain the system's screen resolution.
Tested on my Fedora Silverblue Desktop and my Aya Neo Mini PC with PlaytronOS 0.12.1.21.
Introduces an `extended` option to the `hwctl system-info` command for backwards compatibility.
> PTCORE-222 add extended option to system-info with resolution

- README.md
- usr/lib/udev/rules.d/50-lenovo-legion-controller.rules
They are available upstream as of Linux 6.8-rc3. The latest PlaytronOS build is using Linux 6.8.11.
> Remove Legion Go udev rules

- usr/share/polkit-1/rules.d/50-one.playtron.hwctl.rules
Allow hwctl to be run with pkexec. Needed so playserve can do drive formatting without requiring a password.
> allow hwctl to be called with pkexec

- usr/bin/playtronos-update
Converts rpm-ostree upgrade/rebase output to the format:
PERCENT_COMPLETE%: COMPLETED/TOTAL MB
e.g. 55%: 55.0/100.0 MB
Under some conditions, such as if the update is already downloaded, no output will be written.
To handle these cases, any consumer of this output should start at 0% and set progress to 100% when the process exits.
**Testing**
Tested by copying over the modified `playtronos-update` script to a PlaytronOS device and using it to run updates between 0.17.2.55 and 0.17.2.57 back and forth multiple times.
> add easily consumable progress reporting for rpm-ostree download operations

- usr/bin/hwctl
- added `has-brightness-control` display sub-command to check if brightness controls can be used, addresses https://playtron-one.atlassian.net/browse/PTCORE-2049
- `hwctl display has-brightness-control` will give a return code of `0` if brightness controls can be used, any other value should be interpreted as brightness controls being unavailable
- added the ability to raise and lower brightness and volume by a specific relative amount, some examples:
- `hwctl display set-brightness +50` will raise brightness by 50
- `hwctl display set-brightness -10` will lower brightness by 10
- `hwctl display set-brightness 30` will set the brightness to 30 (existing functionality)
- `hwctl audio set-volume +10` will raise audio volume by 10
Being able to set the relative value is meant to address …
> Various hwctl improvements

- usr/bin/hwctl
This seems to do the trick and fixes permissions issues on external drives after formatting and on subsequent boots/mounts. Although I am not quite sure why.
> PTCORE-1850 fix disk permissions when formatting

- etc/xdg/weston/weston.ini
Firefox is no longer installed.
Running the Steam client can cause issues with Playserve.
> Remove Weston shortcuts

- usr/lib/systemd/system-preset/50-playtron.preset
This service will kill off processes when tmpfs becomes fully utilized. Since we only have a few major processes running, this can cause more harm than good.
> Disable systemd-oomd.service

- usr/bin/hwctl
You can set the timezone with `pkexec hwctl datetime set-timezone <timezone>`
Where `<timezone>` is a value from the list given by `timedatectl list-timezones`.
Tested and working on my local system.
> add functionality to set timezone

- README.md
- etc/security/limits.d/50-playtron.conf
- usr/lib/sysctl.d/50-playtron.conf
- usr/lib/sysctl.d/50-swappiness.conf
and increase the allowed number of mapped memory areas a process can use. This helps to get more games running.
> Increase open file limit

- README.md
- usr/bin/playtron-factory-reset
- usr/lib/sddm/sddm.conf.d/55-playtron.conf
- usr/lib/systemd/system-preset/50-playtron.preset
- usr/share/lightdm/lightdm.conf.d/55-playtron.conf
Tested factory reset by updating files manually on an existing PlaytronOS install, creating/editing files in all the sddm related locations under /etc, and running the factory reset script. Then confirming the files/edits were removed.
> OS-117 switch display manager to sddm

- usr/bin/hwctl
**Why**:
Currently, Grid handles changing log level, the environment (red/black/prod), and enabling/disabling ssh. It does this by using sudo and a password.
Adding this functionality to hwctl allows Grid to call the script without a password or using sudo since hwctl can already be called with elevated privileges using pkexec.
**How**:
- Added an `ssh` subsystem with `enable` and `disable` commands which call `systemctl`.
- Added an `environment` subsystem with `set` and `clear` commands which modify config files under `~/.config/environment.d` which is read by the gamescope session at startup.
- The `environment` subsystem allows setting any environment variable by creating a separate config file based on the environment variable name to prevent the variables overwriting each other, …
> OS-206 add ssh and environment controls

- usr/bin/resize-root-file-system.sh
The `resize-root-file-system` script was failing on bootc builds using composefs.
> fix resize root on bootc builds

- usr/share/inputplumber/devices/25-playtron-ayaneo_2.yaml
- usr/share/inputplumber/devices/25-playtron-ayaneo_2s.yaml
- usr/share/inputplumber/devices/25-playtron-legion_go.yaml
- usr/share/inputplumber/devices/25-playtron-msi_claw.yaml
- usr/share/inputplumber/devices/25-playtron-rog_ally.yaml
- usr/share/inputplumber/devices/25-playtron-rog_ally_x.yaml
- usr/share/inputplumber/devices/25-playtron-steam_deck.yaml
This change adds PlaytronOS-specific device configuration for several devices to enable touchscreen support by default. InputPlumber will try to load/match device configuration in numerical order, so prefixing the config name with `25-` will make InputPlumber considered these config before ones with `50-`.
> [!NOTE]  
> This change will require the generic touchscreen support in InputPlumber to be merged before including these overrides.
> add inputplumber config overrides

- usr/share/inputplumber/devices/25-playtron-ayaneo_2.yaml
- usr/share/inputplumber/devices/25-playtron-ayaneo_2s.yaml
- usr/share/inputplumber/devices/25-playtron-legion_go.yaml
- usr/share/inputplumber/devices/25-playtron-msi_claw.yaml
- usr/share/inputplumber/devices/25-playtron-rog_ally.yaml
- usr/share/inputplumber/devices/25-playtron-rog_ally_x.yaml
- usr/share/inputplumber/devices/25-playtron-steam_deck.yaml
This change modifies the InputPlumber device configuration to capture all keyboard devices to listen for meta and volume key events.
> capture all volume/meta keys

- etc/xdg/weston/weston.ini
- usr/bin/playtron-weston
- usr/bin/playtronos-session-select
- usr/libexec/playtron/dev-session-trigger
- usr/share/polkit-1/rules.d/50-one.playtron.playtronos-session-select.rules
- usr/share/wayland-sessions/playtron-weston.desktop
This PR allows for pressing L1+R1+Y+Left Stick button in the first 30 seconds of the playtron session to activate the dev session.
Sibling PR: https://github.com/playtron-os/gamescope-session-playtron/pull/7
- playtronos-session-select
- move script from gamescope-session-playtron into this project (recommend to check the commit level diff to see the changes made to the session select script)
- add a `--no-switch` flag for setting the session type without actually switching the session
- stop inputplumber when starting dev session to make touchscreen work
- set 2x scaling to make touch screen more usable in weston on Aya Neo 2
- add a weston wrapper (playtron-weston) to allow making the dev session transient
- add `dev-session-trigger` python script which watches InputPlumber events via …
> Add dev session trigger

- usr/bin/playtronos-session-select
- usr/libexec/playtron/dev-session-trigger
Switching immediately into the dev session would cause the touch screen on the Aya Neo 2 to not function sometimes, even with the work around in place.
Instead, when the button combo is pressed, switch to the dev session (without actually performing the switch), then reboot.
Upon reboot, the dev session will start immediately and the touchscreen works 100% of the time.
> reboot into dev session after trigger

- usr/lib/udev/hwdb.d/59-sui.hwdb
- usr/share/inputplumber/devices/25-playtron-suiplay0x1.yaml
This change updates the inputplumber config for the SuiPlay 0x1 to capture the bmi323 gyro/accelerometer. It also includes a new hwdb entry that will correctly map the keyboard the device uses to send key combos with F[15-18] keys.
> [!NOTE]
> We will need to run `sudo systemd-hwdb update` somewhere in the build process to ensure that the new hwdb rule is included in the db.
> Update 0x1 config and add hwdb entry for keyboard

- usr/lib/systemd/system-preset/50-playtron.preset
Powerstation is required for the hardware testing tool to be able to set a TDP limit.
> enable powerstation service

- usr/lib/udev/rules.d/50-ayaneo2s.rules
- usr/lib/udev/rules.d/50-suiplay0x1.rules
- usr/libexec/playtron/hardware-test-tool
This change adds a test for the serial interface and a udev rule to allow accessing the gamepad serial interface as the normal `playtron` user.
The udev rule works by matching any device node with the name `ttyS2` and uses `IMPORT{program}` to set a udev environment variable on the device called `ID_PRODUCT_NAME` with the product name. Then, if `ID_PRODUCT_NAME` matches "SuiPlay0X1", we apply the permissions/ownership to the device node. If the product name does _not_ match, then this rule will do nothing, so it should not affect any other devices that may also have a `ttyS2`.
The test itself will send a pre-written payload to the serial interface and will pass if we get back the expected response.
> Add serial test and udev rule to access serial interface

- usr/libexec/playtron/hardware-test-tool
There was a gap in the timings, allowing the else condition to be activated, exiting the test prematurely.
> fix speaker test

- usr/libexec/playtron/dev-session-trigger
Sibling PR: https://github.com/playtron-os/gamescope-session-playtron/pull/9
When the FTUE starts, `~/.local/share/playtron/tools` does not exist, so using the existence of this directory as a proxy for FTUE completion.
We check every 30 seconds if the directory exists so that we do not run forever on first boot.
The playtron session has a similar check (see sibling PR) so that this trigger script is completely skipped on subsequent boots.
Testing procedure:
- start system
- leave it on the FTUE for a few minutes
- press button combo
- allow system to restart into dev session
- open hardware testing tool
- select power off
- turn on system again
- complete FTUE
- wait a few minutes
- attempt button combo a few times
- system does not reboot
- check that dev-session-trigger process is not …
> run trigger until FTUE completes

- usr/bin/hwctl
- usr/libexec/playtron/hardware-test-tool
- usr/libexec/playtron/stress-test-speaker
- add audio input settings to hwctl
- add audio input and output settings to the hardware testing tool
- remove any automatic volume settings done by individual tests
- set a global default volume for input and output at startup of the hardware testing tool
- rearrange test tiles to fill gaps
- separate action and settings tiles from test tiles
> Add volume settings

- usr/lib/systemd/user/pipewire-rnnoise-switch.service
- usr/libexec/playtron/hardware-test-tool
The wpctl command being run by the service was failing to set the default output, so I fixed that as well.
> ensure noise filtering is enabled when starting the hardware test tool

- usr/share/inputplumber/devices/24-playtron-ayaneo_2s_v2.yaml
- usr/share/inputplumber/devices/24-playtron-suiplay0x1_v2.yaml
This change updates the bios glob pattern to match bios versions `2.19` - `9.99`
> update bios glob pattern for future bios releases

- usr/libexec/playtron/hardware-test-tool
Change default volume levels for the hardware test tool by request.
Tested these levels manually with the speaker test to make sure the levels were reasonable.
> Adjust default volume levels for test tool

- usr/bin/hwctl
Can be run with `hwctl firmware`.
Sample output:
```
{
"Devices": [
{
"DeviceId": "21ba7fbcdfb80c824895aad926418475726bcc79",
"Name": "Navi 32 [Radeon RX 7700 XT / 7800 XT]",
"Vendor": "Advanced Micro Devices, Inc. [AMD/ATI]",
"Version": "100",
"UpdateVersion": "101"
},
{
"DeviceId": "71b677ca0f1bc2c5b804fa1d59e52064ce589293",
"Name": "SSD 970 EVO Plus 1TB",
"Vendor": "Samsung",
"Version": "2B2QEXM7",
"UpdateVersion": null
}
]
}
```
If an update is not available for a device, "UpdateVersion" will be null.
The devices can be updated with the command `fwupdmgr update <device id 1> ... <device id n>`, or just `fwupdmgr update` to update all devices.
> OS-353 add `firmware` command to print system firmware information

- usr/bin/hwctl
- Introduce `hwctl firmware update`, a simple wrapper around `fwupdmgr update`
- Move the existing `hwctl firmware` command to `hwctl firmware info`
Initially planned to have `fwupdmgr update` called directly since the wrapper doesn't really do much, however, that would require configuring elevated privileges for that command. Having `fwupdmgr update` called through `hwctl` allows us to reuse the elevated privileges already afforded to `hwctl`.
Make sure to call the command like so: `pkexec hwctl firmware update <device id>`.
> add firmware update functionality

- usr/bin/playtronos-systemreport
This change adds a new `playtronos-systemreport` command which will collect a variety of logs and system state that can be very useful for reporting bugs and troubleshooting.
The script collects a variety of information and creates a tar archive with all the information in various reports.
> Add 'playtronos-systemreport' command to collect logs and system info

- usr/bin/playtron-factory-reset
This allows the full factory reset to work even if a user is currently using a local container image.
> Switch to latest OS build during factory reset
